### ISSUE TITLE
Error in Web3Client.getTransactionReceipt 

### ISSUE THREAD

**Issue by chnejohnson** [simolus3/web3dart#143]
- This error just happened in sometimes, not always.
- In my use case, I call this function per second.

Error Output
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
c
^
#0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
#2      int._parse (dart:core-patch/integers_patch.dart:100:12)
#3      int.parse (dart:core-patch/integers_patch.dart:63:12)
#4      hexToDartInt
package:web3dart/…/crypto/formatting.dart:59
#5      new TransactionReceipt.fromJson
package:web3dart/…/core/transaction_information.dart:107
#6      Web3Client.getTransactionReceipt.<anonymous closure>
package:web3dart/…/core/client.dart:239
#7      _rootRunUnary (dart:async/zone.dart:1362:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#11     Future._propagateToListeners (dart:async/future_imp<…>

```

Source Code
```dart
class TransactionReceipt {
    ...
    TransactionReceipt.fromJson(Map<String, dynamic> map)
          : transactionHash = hexToBytes(map['transactionHash'] as String),
            transactionIndex = hexToDartInt(map['transactionIndex'] as String),
      ...
```

```dart
int hexToDartInt(String hex) {
  return int.parse(strip0x(hex));
}
```

**Comment by simolus3** [comment]
Which `web3dart` version are you using? I think this has already been fixed, can you try using the `2.0` prerelease?
