### ISSUE TITLE
[BSC] Error in client.estimateGas

### ISSUE THREAD

**Issue by ndangan094** [simolus3/web3dart#144]
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: RPCError: got code -32000 with msg "missing from address".
#0      JsonRPC.call (package:web3dart/json_rpc.dart:49:7)
<asynchronous suspension>
#1      Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:60:20)
<asynchronous suspension>
#2      Web3Client.estimateGas (package:web3dart/src/core/client.dart:355:23)
<asynchronous suspension>
#3      CurrentController.getTransactionFee (package:sota_wallet/controllers/currentController.dart:30:19)
<asynchronous suspension>
```

**Comment by simolus3** [comment]
Well, did you set a from address?
