### ISSUE TITLE
when update flutter to version 2 issues transfer erc20

### ISSUE THREAD

**Issue by athlona64** [simolus3/web3dart#196]
```
E/flutter (28730): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter (28730): 
E/flutter (28730): ^
E/flutter (28730): 
E/flutter (28730): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (28730): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:522:7)
E/flutter (28730): #2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
E/flutter (28730): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter (28730): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter (28730): #5      JsonRPC.call (package:web3dart/json_rpc.dart:52:23)```

```
       final transaction = await client.sendTransaction(
          credentials,
          Transaction.callContract(
            from: ownAddress,
            contract: contract,
            function: transfer,
            maxGas: gasClaim,
            gasPrice: EtherAmount.inWei(BigInt.from(10 * 1e9)),
            parameters: [receiver, amount.getInWei],
          ),
          chainId: chainId,
        );

```



before update flutter is work

**Comment by athlona64** [comment]
i found the solution if non specify nonce parameter above issue will be happen must specify nonce parameter manual.
