### ISSUE TITLE
On Ganache V 7.0.0 I am receiving an rpc error "Unhandled Exception: RPCError: got code -32700 with msg "Invalid signature v value"."

### ISSUE THREAD

**Issue by reuben21** [simolus3/web3dart#240]
` [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RPCError: got code -32700 with msg "Invalid signature v value".
E/flutter ( 6446): #0      JsonRPC.call (package:web3dart/json_rpc.dart:62:7)
E/flutter ( 6446): <asynchronous suspension>
E/flutter ( 6446): #1      Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:54:20)
E/flutter ( 6446): <asynchronous suspension>
E/flutter ( 6446): #2      PharmacyModel.writeContract (package:bic_android_web_support/providers/provider_pharmacy/model_pharmacy.dart:64:30)
E/flutter ( 6446): <asynchronous suspension>`

**Comment by reuben21** [comment]
https://github.com/trufflesuite/ganache/blob/develop/UPGRADE-GUIDE.md
