### ISSUE TITLE
SocketException: Failed host lookup: 'ropsten.infura.io' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by iceman750** [simolus3/web3dart#27]
Using Ropsten and infura as an api provider. For some reason I keep getting this error. Anybody know why?

```
I/flutter (10196): SocketException: Failed host lookup: 'ropsten.infura.io' (OS Error: No address associated with hostname, errno = 7)
E/flutter (10196): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter (10196): SocketException: Failed host lookup: 'ropsten.infura.io' (OS Error: No address associated with hostname, errno = 7)
E/flutter (10196): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter (10196): #3      JsonRPC.call (package:web3dart/src/io/jsonrpc.dart:32:31)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #4      Web3Client._makeRPCCall (package:web3dart/src/web3client.dart:29:30)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #5      Web3Client.getTransactionCount (package:web3dart/src/web3client.dart:155:10)
E/flutter (10196): #6      FinalizedTransaction._asRaw (package:web3dart/src/transaction.dart:98:48)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #7      FinalizedTransaction.send (package:web3dart/src/transaction.dart:114:10)
E/flutter (10196): #8      _MyHomePageState.test (package:flutter_web3/main.dart:59:10)
E/flutter (10196): <asynchronous suspension>
E/flutter (10196): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (10196): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (10196): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (10196): #12     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (10196): #13     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (10196): #14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (10196): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
E/flutter (10196): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (10196): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (10196): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (10196): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (10196): #20     _invoke1 (dart:ui/hooks.dart:173:13)
E/flutter (10196): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:127:5)
```

**Comment by iceman750** [comment]
Solved!
